# GLOBAL CONFIGURATION

spring:
  application.name: service-one
  jackson.serializationindent_output: true

info:
  component: Service-One
  artifact: service-one
  version: 5.0.0

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

management:
  contextPath: /actuator
  security.enabled: false

server:
  contextPath: /
  port: 8082

---
#DEFAULT CONFIGURATION
spring:
  profiles: default
  autoconfigure.exclude:
    - org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration
  cloud:
    consul:
      host: '127.0.0.1' #<CONSUL_HOST>
      port: 8500
      discovery:
        hostName: '<HOSTNAME>'
        instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
        healthCheckInterval: 15s
  data:
    mongodb:
      host: '127.0.0.1:27017' ## <MONGODB_HOST>
      username: 'epam' #<MONGODB_USER>
      password: '123456' #<MONGODB_PASSWORD>'
      database: admin #service_one
  rabbitmq:
    host: '<RABBITMQ_HOST>'
    port: 5672
    username: 'epam' #<RABBITMQ_USER>'
    password: '123456' #<RABBITMQ_PASSWORD>'
    virtualHost: /

# logstash.servers: logstash:5000

logging:
  level:
    org.springframework.web: DEBUG
    com.mudigal.one: DEBUG
    org.hibernate: DEBUG
